appconfig.tf
cloudwatch.tf
cognito.tf
dynamodb.tf
ecs_service.tf
ecs_task_definition.tf
iam.tf
modules/linked-account/README.md
modules/linked-account/data.tf
modules/linked-account/locals.tf
modules/linked-account/main.tf
modules/linked-account/variables.tf
outputs.tf
security_group.tf
sns.tf

A TF sub module for creating roles and policies for linking accounts. 
Added outputs to main module to use in this sub module

CSS-887 Linked Account sub module

---

locals.tf

Release console and agent v7.06.004.

Release console and agent v7.06.004.

---

README.md
iam.tf
modules/linked-account/README.md
variables.tf

Add a section on cleaning up the install 
Switch large outputs descriptions to <<EOF
Fixed URLs and sub-module source
Included changes from old repo

Documentation cleanup

---

locals.tf

Increment versions for 7.07.000 release.

Increment versions for 7.07.000 release.

---

iam.tf

Add missing service quota permission for gp3 volumes.

CSS-1110 Add missing service quota permission for gp3 volumes.

---

locals.tf

Release v7.08.000

---

locals.tf

Increment versions for 7.08.002 hotfix release.

Increment versions for 7.08.002 hotfix release.

---

locals.tf

Update image versions for v7.09.000 release.

Update image versions for v7.09.000 release.

---

appconfig_schema.json

Add new property to the SSM Schema

CSS 1013 Add classification last updated property

---

README.md
ecs_task_definition.tf
iam.tf
variables.tf

Adding bedrock policy and a var to add it. 
Added a warning to readme.

CSS-1048/CSS-1195 add bedrock policy

---

dynamodb.tf
ecs_service.tf
ecs_task_definition.tf
iam.tf
locals.tf
s3.tf
variables.tf

- Renamed Reports bucket in favor of a general Application bucket for the entire deployment
- Renamed Reports DDB table to DashboardReports and changed Partition Key and Sort Key

CSS 902 Renamed DDB table and S3 bucket

---

locals.tf

Increment versions for v7.10.000 release.

Increment versions for v7.10.000 release.

---

iam.tf

Add permissions to load SNS Subscriptions from Agents

CSS 1362 Fix Agent SNS permissions

---

ecs_task_definition.tf

Changed slightly the console health check timeout and grace period

CSS 1311 Console health check changes

---

locals.tf

Increment versions for v8.00.000 release.

Increment versions for v8.00.000 release.

---

appconfig_schema.json

Add console URL to app config schema.

Add console URL to app config schema.

---

cognito.tf

CSS-1383 Create ReadOnly Cognito group

---

s3.tf

Add the resource policy requested by some customers to mitigate warnings.

css-1432 Add SSL Secure Transport restriction for the CSS Application Bucket

---

dynamodb.tf

- DynamoDB changes
- removed AccountIdAndGuid GSI
- added AccountIdResultTypeAndDateTime GSI

CSS 1370 Classification Results adjustments

---

dynamodb.tf

- Added new malware detection table

CSS-1108 Malware detection table

---

dynamodb.tf

Add removed GSI back to ClassificationResults table which will be removed in a future release instead.

CSS-1459 Add removed GSI back to ClassificationResults table

---

iam.tf

Fix reference to bedrock policy.

Fix reference to bedrock policy.

---

locals.tf

Increment console image version to v8.00.001.

Increment console image version to v8.00.001.

---

locals.tf

Increment image versions to v8.01.000.

Increment image versions to v8.01.000.

---

locals.tf

Increment image versions to v8.01.001.

Increment image versions to v8.01.001.

---

ssm.tf
variables.tf

Add auto scaling Azure agent parameters to ssm.

CSS-1373 Add autoscaling Azure Agent settings

---

locals.tf

Increment image versions to v8.02.000.
**Do not merge until after prod release of v8.02.000.**

feat: Increment image versions to v8.02.000.

---

dynamodb.tf

This reverts commit 6c97f188b94ec3ee1959f9ae2cd11f0886d3232b.

Revert "CSS 1508 Remove DDB Azure GSI2"

---

ecs_task_definition.tf
variables.tf

Allow product_listing to be set as BYOL. 
Fix some copy paste text leftovers.

CSS-1691 Add BYOL mode support

---

locals.tf

Increment image versions for v8.04.000 release.

feat(v8.04.000): Increment image versions for v8.04.000 release.

---

locals.tf

chore(Release v8.04.001): Increment image versions for v8.04.001 release.

chore(Release v8.04.001): Increment image versions for v8.04.001 release

---

ecs_task_definition.tf
iam.tf
locals.tf
sqs.tf
variables.tf

Added KMS Keys support for SQS and SNS for the Console and Agent regions.

css-1454 Add KMS Key support for SQS and SNS

---

variables.tf

chore(clamAV): CSS-1799 Rename ClamAV to CSS Secure

---

modules/linked-account/main.tf

Need this to tag objects in versioned buckets.

feat(CSS-1981): Add PutObjectVersionTagging permission to LA Submodule

---

locals.tf

Bump image version to v8.08.000

Bump image version to 8.08.000

---

locals.tf

Bump version to v8.08.001

---

dynamodb.tf

fix(css-2076): Make table match CFT definition

---

locals.tf

Bump images version to v9.00.000

chore(bump version): Bump images version to v9.00.000

---

ecs_task_definition.tf
variables.tf

Terraform support for Console CPU and Memory

feat(css-2065): Support for Console Task CPU and Memory configuration

---

locals.tf

Bump versions to v9.01.001

---

locals.tf

Update version to match with last release v9.01.002

feat: bump version to v9.01.002
